### ISSUE TITLE
Implement following functionalities

### ISSUE THREAD

**Issue by arshadkazmi42** [bibekluitel/JMON#4]
- [x] stringify() // Done by @arshadkazmi42 PR: #8 
- [ ] isCreated()
- [ ] isUpdated()
- [ ] isDeleted()
- [ ] print()
- [ ] set() // InProgress by @bibekluitel 
- [ ] get()
- [ ] add() // Not sure if this is needed
- [ ] commit() // InProgress by @arshadkazmi42 

Please mark the tasks which are getting completed

**Comment by bibekluitel** [comment]
Lets create a file for a function inside a lib folder. 

Like 
 ```
lib\
    >set.js
    >print.js
```

And we can import these and assign them to object protoType. A good  outcome to do this will be minimum number of conflicts.

**Comment by arshadkazmi42** [comment]
Closing this, as we have changed the approach
